### ISSUE TITLE
Possibility to customize `outsideClick` behaviour

### ISSUE THREAD

**Issue by sp4m** [dangrossman/bootstrap-daterangepicker#1156] opened 2016-07-05 13:13 UTC
This issue was sort of adressed in #328 two years ago but I still think it's a pretty relevant in terms of user experience. Normally a click outside a dropdown or an overlay cancels any changes made.

In my scenario I want the user to specifically click "Apply" before any changes are made to the input as the input `change` event triggers loading of a large dataset. As I see it there are a couple of ways to handle this:

- It's already possible to hook into the `cancel.daterangepicker` event, so why not add an `outsideClick.daterangepicker` event as well? They're clearly not doing the same thing. In that case a solution would look something like this:
```
$('#daterange').on('outsideClick.daterangepicker', function(ev, picker) {
  picker.startDate = picker.oldStartDate;
  picker.endDate = picker.oldEndDate;
});
```

- Add a new option as suggested in the referenced issue and simply check for that in the `outsideClick` method and revert the dates if true. Less flexible but easier to understand and use.

Some might not agree with or care about this change in the flow but I'd argue it's way more intuitive, it only requires a small addition to the code, and it's completely optional.

**Comment by dangrossman** [comment] 2016-07-05 15:07
Quick fix: If you only want to react to the user explicitly applying the change, listen to the `apply.daterangepicker` event instead of the `change` event of your input.

**Comment by sp4m** [comment] 2016-07-05 16:08
My second paragraph was pretty poorly worded, as I already do that with `autoUpdateInput: false`. The issue appears when the user modifies the range without applying it. If the user triggers `clickCancel` the range will be reset but not on `outsideClick` which seems pretty inconsistent to me.

Again, I don't believe everyone agrees with me on this one but I think there should be a way to enable this behaviour.

**Comment by dangrossman** [comment] 2016-07-05 16:10
I understand your concern, and I'll think on it, which is why I didn't close the issue

But my "quick fix" is "a way to enable this behaviour" with the current library

**Comment by kylefarris** [comment] 2016-07-08 18:47
I'm actually thinking I need something like what @sp4m is mentioning as well. My scenario is that I have a `singleDatePicker` and the only way it functions properly is to set `autoUpdateInput: true` which technically makes sense. 

The problem is if someone brings focus to the field (which is blank by default) on accident (or tabs through to get to another field beyond it), the field is populated with whatever date was selected by default even if they didn't click on the date explicity. Since there is no cancel button on single date pickers, there's no way to clear the date. Even deleting the value from the field manually doesn't work--it's just repopulated with the auto-selected value in the picker.

Maybe a solution in my case would be for there to be no default/auto-selected date in the picker? Is that possible?

Either way, it would be nice to somehow be able to clear a single date picker field--not sure of the best solution for that though.

**Comment by dangrossman** [comment] 2016-07-08 18:51
@kylefarris 

Set `autoUpdateInput: false`, or make your own clear button

https://jsfiddle.net/4wkubbbw/1/

**Comment by kylefarris** [comment] 2016-07-08 19:02
@dangrossman 

Thanks for the quick response! You'll notice that in your fiddle, if you set `autoUpdateInput: false`, you actually can't select a date at all anymore. The clear button is cool idea but, unfortunately, it's just not going to get past our QC/UX team. I'll be happy to do the work to get this functionality but I'd like your input on how best to approach it since you're much more familiar with the code base. 

-Kyle

**Comment by kylefarris** [comment] 2016-07-08 19:03
Oh, and thanks for the awesome plugin! :+1:

**Comment by dangrossman** [comment] 2016-07-08 19:05
If you set `autoUpdateInput: false`, you have to update your input yourself when a new date is selected, hence the name of the option. You're still notified of this selection via a callback function and the apply event. You write your own code to put the new date into the input, or whatever you want to do with it.

http://www.daterangepicker.com/#ex5

**Comment by sp4m** [comment] 2016-07-08 19:18
The issue @kylefarris has is already handled pretty well by the plugin, as @dangrossman just pointed out.

I suggested two solutions in my first post but I failed to accurately describe my problem until my second post, which is causing some unnecessary confusion. Anyway, in my opinion both of my suggested solutions are pretty unoptrusive and ensures a consistent user experience (if desired). Once again, I'm talking about what should happen if the user selects a range but doesn't immediately apply it.

**Closed** 2016-07-08 19:25 UTC
