### ISSUE TITLE
Cannot modify start/stop on DateRange after initial values set

### ISSUE THREAD

**Issue by dmarginian** [dangrossman/bootstrap-daterangepicker#1166] opened 2016-07-15 16:40 UTC
This issue can be reproduced on the "Date and Time" example - http://www.daterangepicker.com/.

Open the date range picker and choose both a start and a stop date.  Next, attempt to modify the stop date by focusing on the stop date text input and selecting a new date via the calendar display (not directly withing the input).  Notice when you hover new values on the calendar the value in the stop date field is not updated.  When you select a new date the input's value does not update either.  You must reselect a start date to set a new stop date.  

Looking at the code this appears to be by design and a result of the values being set on hover verse on click.

**Comment by dangrossman** [comment] 2016-07-15 16:41
This is already fixed in commit https://github.com/dangrossman/bootstrap-daterangepicker/commit/de4c4e2b8d266385bebf3303830f05048e42f08f

**Closed by dangrossman** 2016-07-15 16:41 UTC

**Comment by dmarginian** [comment] 2016-07-15 17:25
Thanks for the quick response.  I tried that and there is still a bit of inconsistet behavior.  Normally the input's value is updated on hover.  The input's value is not updated on hover in this case (because and endDate has been set, ~1254ish).

In general is it critical for the input value to be updated on hover? If I set a start/stop immediately after setting the stop the start date is focused and the value is updated to the stop date I just entered.  Only when I mouse off of the calendar is the start input set back to the original value set.  I don't see much value in updating the input's value on calendar hover as a user can see what they are hovering.  It seems more intuitive for the input's value to change only on selection.  

If there is no critical reason to update the inputs on hover I would propose adding a config option (updateInputsOnHover: boolean) and allow user's to disable this behavior.  I can submit a PR for this if you find it acceptable.

**Comment by dangrossman** [comment] 2016-07-15 17:27
I disagree. I will not accept that PR. This is years-old behavior nobody has had an issue with.

**Comment by dmarginian** [comment] 2016-07-15 17:36
The PR would not change the default behavior - it would just allow for the flexibility to change it.  

My user's aren't super savy but I agree with them in this instance.  After setting a stop it is not intuitive that the start is immediately set to the stop that I just entered.  And then when I hit apply it changes back to the start I originally chose?  Very strange and confusing.  

Regardless, there is an inconsistency with de4c4e2's resolution.  If the input's value is normally updated on hover, it should also be updated on hover when the input is selected and new values are chosen in the calendar.

**Comment by dangrossman** [comment] 2016-07-15 17:37
I don't know what you're talking about with things changing back and forth. Showing what you're hovering over does not change any selections.

**Comment by dmarginian** [comment] 2016-07-15 17:51
What I am describing was introduced in de4c4e2 (or some other commit). Set a start date by clicking on a day in the calendar.  Set a stop date by clicking on a day in the calendar.  Immediately after setting the stop date the start date is brought into focus and the input value of the start date is set to the value that I just set for stop date.  If I the go over to the Apply button the start date is set back to the correct date. If I switch back to 2.1.23 I do no see this behavior.

**Comment by dangrossman** [comment] 2016-07-15 17:55
That's how it's worked for 4 years. It's not a bug. The input is *supposed* to show what you're hovering over.
