### ISSUE TITLE
End Time Being selected on its own 

### ISSUE THREAD

**Issue by loushps** [dangrossman/bootstrap-daterangepicker#1065] opened 2016-04-25 15:35 UTC
1) Select a start date 
3) place the cursor on Day 1 in the current month 
4) Move the cursor up to the start date textbox and only change the year to 1 year in the past 

Result: 
the start date will be the one chosen by the user one year in the past 
however the end date will be the date where the user last hovered the cursor over before changing the year of the Start Date 

as a suggestion, Provide an option to prevent the End Date from getting set when hovering over the calendar

**Comment by dangrossman** [comment] 2016-04-25 16:00
I wasn't able to reproduce the issue using those instructions. I also have very little time to develop any new features for this library. If there is a bug, you'll have to provide better reproduction steps if you want me to look into it. If this is a feature request, you'll need to program it yourself.

**Comment by dangrossman** [comment] 2016-04-26 02:59
Closing due to no followup

**Closed by dangrossman** 2016-04-26 02:59 UTC
